# Node map: title -> obj_token (only leaf/article nodes, skipping already-processed)
$nodeMap = @{
    # 0导航与索引 - already processed, skip these 3
    # "对接人与售后入口速查" = "LRkxd3CofoTapmxPa8Uc7eLlnWd"
    # "常用词汇表" = "JH36dwe1hothQexdMppcphvOnLe"
    # "高频问题解答（FAQ）" = "SFFydRX2SoHgPuxwEbUcyXw6nIf"

    # Section/index nodes (no frontmatter expected, skip)
    # "发票云运营知识库" = "GnwpdCTX0ogDC3xWtUgctueZnWc"
    # etc.

    # 金蝶中国渠道 - leaf articles
    "1.1.1 产品及解决方案咨询" = "FBiDdyiEPojvLBx90zxcLoTVnpe"
    "1.1.2 售前顾问预约操作指引" = "LbZ7dLZ1WoyvvkxdlkhczSSAnWQ"
    "1.1.3 产品报价获取" = "ML7zdqQVMosISUxCnLRcspSDnQz"
    "（1）开票标准版申请试用流程_金蝶" = "CmtAdLjTtou18wx1Hf5cFkJinh7"
    "（2）收票标准版申请试用流程_金蝶" = "CF9WdBaPNoJu2ox4uBKcgrmenhd"
    "（3）影像标准版申请试用流程_金蝶" = "Yml2dVAqwod1DCxgy9Acn6Fun2W"
    "（4）开票旗舰版申请试用流程_金蝶" = "HJENdA0FPolFBdxyONac8pxonMd"
    "（5）收票旗舰版申请试用流程_金蝶" = "JLf6drldLoxLTVxRgYncMPcXnyh"
    "（6）影像旗舰版申请试用流程_金蝶" = "VGkWdk0GioHYnDxq0WhcnM3xnZd"
    "（7）开票星空旗舰版申请试用流程_金蝶" = "LUs5dNBjKoHtdnx4p30czVVDnBh"
    "（8）收票星空旗舰版申请试用流程_金蝶" = "QEeRdEypWoUPHUxMov2cxWagnvh"
    "1.2.1 第三方询价合同流程说明" = "ZzqSdNgz9o5NdPxB0bvcmIDmnmb"
    "1.2.2 KBC签订合同变更流程" = "PndjdsFXpogiqKx4O1Gcv360nAe"
    "1.3.0 订单分类说明" = "G7gzdXUcqoTl2PxcH5TcOEo0n9c"
    "01KBC上架产品-直分销下单流程" = "MNDvdKDP9ov3H0xZQdzczsZgnEg"
    "02KBC未上架产品订单-第三方询价订单流程" = "UlQEdDFHWohUu5xEATwcOEwCn7f"
    "03KBC订单信息变更操作指引" = "HVOVdXFUHo2EE8xRI3kchgpen8b"
    "04订单到期管理" = "A8vKdVNB3oznNgxv8Nfc7T0VnAe"
    "05订单退货不退款流程" = "EefedO5xYol9YpxqUQecvwgPnaf"
    "特批订单转正统计_金蝶" = "GUL5d6NqOoV9VTx82I9cMLHanyh"
    "提前开通申请流程-标准版产品_金蝶新购" = "ZJT4dVnOyoABzXx5pqNc22cWndb"
    "提前开通申请流程-旗舰版产品_金蝶新购" = "JtV1duiojor4MFx0EuucbJhKnrb"
    "产品延期特批申请流程-标准版产品_金蝶续费" = "AamLdBgivowfHgxv3QBcWHfjnpg"
    "产品延期特批申请流程-旗舰版产品_金蝶续费" = "KFr2dnFSZo31qXxLP6rc2SfWnDf"
    "开票收票标准版产品授权激活流程_金蝶公有云" = "Od9BdQcrhoEBJhxJAt4czu6Tnme"
    "影像标准版授权激活流程_金蝶公有云" = "KLN9dSRjgounrLx24VrctLRQncd"
    "旗舰版产品许可分配流程_金蝶公有云" = "Xb3rdKgkCoibXKxSg3NckY3anI6"
    "星空旗舰版许可分配流程_金蝶公有云" = "AGwfdZJi7oCQnVxwOG3cXLwVngR"
    "标准版产品许可分配流程_金蝶私有云" = "TqMpdqTXQoshjYxDlAycUouYnDg"
    "旗舰版产品许可分配流程_金蝶私有云" = "PL8xdWczqojozPxdG73cUaVAnCf"
    "星空旗舰版许可分配流程_金蝶私有云" = "IsXrdlReno06lqxVzZIcO4x4njc"
    "1.5.1 订单结算方式分类说明" = "JKU4djNfwo9OtHxzXBpcSonSnoh"
    "1.5.2 预付款结算流程" = "UYcPdp62QoulbNxBPWlc2XHmnff"
    "1.5.3 后付款结算流程" = "FrIAdsP2oobEkYxX0Huct0UmnMf"
    "1.5.4 回款异常-回款金额不符处理流程" = "WdkFd3rcPoRHf5x8bdOcMljrnCc"
    "1.5.5 回款异常-回款认领错误" = "VaoKdKGcPoMZhaxWNzRctYycn7b"
    "1.5.6 回款异常-回款逾期未到处理流程" = "H7yWdHCyioLxRmx1KnLcJlZKnwh"
    "1.5.7 回款异常-退款与红冲" = "ZqDzd2v8koHatexx6iQcvLQhnCe"

    # 自营渠道 - leaf articles
    "2.1.1 产品及解决方案咨询" = "Of4Ud4Uftolyzaxb2szc7uQ7n8O"
    "2.1.2 售前顾问预约操作指引" = "LhF5dYSk6orS5MxxO0NcOP7wnke"
    "2.1.3 产品报价获取" = "M2HydULxBoyS2cx2I5Lc0DNunLd"
    "（0）自营渠道测试授权申请说明" = "NY7bdfLq3o4BR3xRRh6cm4xcn3c"
    "（1）开票标准版申请试用流程_自营" = "NAF2dwbjTo6Gn1xRStNc9DhMnnd"
    "（2）收票标准版申请试用流程_自营" = "NxvbdJsnNo48fCxvgjscfok8nUd"
    "（3）影像标准版申请试用流程_自营" = "VmhJdI03uorlIuxRIGwcwkzMnkh"
    "（4）开票旗舰版申请试用流程_自营" = "SBgQd2KCEoGCfQxTAPpcYpDjnlb"
    "（5）收票旗舰版申请试用流程_自营" = "Pg6BdBzcxoJvWYxwAwEcYPkrnRg"
    "（7）收票星空旗舰版申请试用流程_自营" = "YUL5d80CcohwOsxe7E6cDNxRnpd"
    "2.2.0 合同类型说明（README）" = "BpBmdAibeoruSAx8omRcSfRNnWd"
    "（1）合同签署方式说明" = "ACFNd7kRLoWM97xPsQrchOGTn2e"
    "（2）合同创建流程-新购、续费、加购" = "L1Dad2rotohA7OxhehqcwrIlnEb"
    "（3）合同审批流程" = "Egvldw7Egoo7bsxG7c8cogfUnNh"
    "（4）合同变更申请指引" = "Opt7dBXyAotaglxrUDEczJbvnmh"
    "（5）合同到期管理" = "SWhFdoWJ6oRR3oxHs1Rc6km9nLb"
    "（6）合同异常处理" = "LqJIdYXAaoT5pyxLEKSc3JWXn5d"
    "01第三方询价合同" = "LHzydh1iKoXTm1xutoacoQ45nGb"
    "（1）标准订单创建来源说明" = "RRECdH3jSom5Gxxp2uNc9bQHnFc"
    "（2）标准订单出库说明" = "MK1bd2tpLo9ZalxzaOIcj4LynFd"
    "（3）订单到期管理" = "FXI7dsL82oTTGex0NkrcLXJBnyt"
    "（4）订单异常处理流程" = "KMExdYwpko08WzxTR96cXrmmnRe"
    "（5）产品退货操作指引" = "WENBdt5U2o74ynxGeoqcaYVCnFb"
    "特批订单转正统计_自营" = "Pqw7d5U91oBOECxxBEncdCMuneH"
    "提前开通申请流程-标准版产品_自营新购" = "E8RgddrvnoIjM6xgaXUcjrzTnth"
    "提前开通申请流程-旗舰版产品_自营新购" = "BjSwdTIHro4jmBx129pcwqa6npd"
    "产品延期特批申请流程-标准版产品_自营续费" = "RCC0dUnKgoRRWXxgJCJcisZLnGf"
    "产品延期特批申请流程-旗舰版产品_自营续费" = "DlXRdlp39o0f99xJdOccQl7Anie"
    "开票收票标准版产品授权激活流程_自营公有云" = "WvkBddPanoBcsaxmwspc21l5ntT"
    "影像标准版授权激活流程_自营公有云" = "V6r1drpXJoNJ1rxShxrcBYlGnYg"
    "旗舰版产品许可分配流程_自营公有云" = "EddWdxemTowI1axEZbicjrd0n4c"
    "星空旗舰版许可分配流程_自营公有云" = "OawMdKQUTo0vTexQ1nlcAg8gnjd"
    "标准版产品许可分配流程_自营私有云" = "WZvBdvLdXofe7lxiVEIcXLPQnhd"
    "旗舰版产品许可分配流程_自营私有云" = "ZWv1diWDwoBmd0xRxwrcgKYXnNg"
    "星空旗舰版许可分配流程_自营私有云" = "ICyhdGdEFo41PexEvCRc3sqSnhd"
    "2.5.1 订单结算方式分类说明" = "Un9sd7tfEoW0K9xUhJnclBaznre"
    "2.5.2 预付款结算流程" = "BG5bdNPyCoYGMwxJ7kkcgKvZnzh"
    "2.5.3 后付款结算流程" = "EbebdL084oeZSIxHTMlcjSFknlg"
    "2.5.4 回款异常-回款金额不符处理流程" = "Dnngdfwc2oNYqOxm2uPcRpQQnHc"
    "2.5.5 回款异常-回款认领错误" = "VcR3doD1foNo5nxQwfscSmXpntb"
    "2.5.6 回款异常-回款逾期未到处理流程" = "PSVMdZEeyodTy9x6vLBc7rUfnhb"
    "2.5.7 回款异常-退款与红冲" = "AjT3dJ6BFoef2kxdk1LcpcaHnOV"

    # MTR 发票云生态伙伴
    "1.1 伙伴加盟-准入与签约操作" = "IjyRdkcCEow48QxxBIKcJch4n3G"
    "1.2 伙伴支持-产品知识及售前支持获取" = "GIN1dMh8aoX1tlxwTjKcx7vMnPe"
    "1.3 伙伴支持-伙伴激励制度说明" = "KozgdxYyMo6JXexnEKDc9o92nLg"
    "1.4 伙伴支持-伙伴升降级申请说明" = "IsX0drYkkoVYuDxR0itcXpDMntf"
    "1.5 伙伴支持-伙伴信息变更操作指引" = "HHpMdbRVvoCSOSx93KBcSvKOnvb"
    "1.6 伙伴订货-产品折扣下单流程" = "GtP0dbSiIojSiBxUMatcrUCUnXc"
    "1.7 伙伴订货-退货退款处理流程" = "CW2dd1kxbo5GcJx0OTzcI1hHnZg"
    "1.8 伙伴退出-保证金退回说明" = "NaX5d7lWMobDCExwO0KcGHdlnjf"
    "1.9 伙伴退出-伙伴退盟申请流程" = "I2gxdMgw9oEgkIx079nc75Rhn4c"
    "伙伴激励审核流程" = "Ojb5ddwJRoAG0BxFe79cet84nCg"

    # MTR 金蝶中国生态伙伴
    "1.1 伙伴订货-KBC分销下单操作指引" = "XLUSd6eznouFvfx5ELTcKjgLnL5"
    "1.2 伙伴订货-KBC直销下单操作指引" = "X9D6dpxCpopr1ixZWvFczabrnZG"
    "1.3 伙伴支持-产品知识及售前支持获取_金蝶MTR" = "RhqLd06ALoenpwxLQsWcLMnInEg"

    # MCR 租户信息变更处理
    "3.1 企业变更租户及合并租户" = "JbpBdHLYgoKAwJxd2z5cO63lnGf"
    "3.2 租户信息变更处理" = "NbBxdUHI6oWAD0x8TSjcc5mZnze"
    "3.3 开票产品使用企业税号及税盘变更操作" = "AD5ydInNPo54Nhx9ambcvEYKnPN"
    "3.4 收票产品使用企业信息变更流程" = "QGUQd3Ju6orX9nx8HFHcMfrLnSh"
    "3.5 租户注销、停用处理流程" = "QqPfdrINcoKZQ5xJlB4czFhpn5c"

    # MCR 租户权益查询
    "1、租户查询平台进入流程" = "VQrrd9iWvoZ7EtxVwh3cZ90Zntf"
    "2、租户权益查看操作指引" = "Cwz6dUccDoSuYUxdItec8TPDnDb"
}

Write-Host "Node map built with $($nodeMap.Count) entries"
